### ISSUE TITLE
机器人处理请求的时候出现异常请问是哪一项配置有问题

### ISSUE THREAD

**Issue by TakayashikiMatsuri** [Cloud-wish/Dynamic-Bot#1]
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

**Comment by Cloud-wish** [comment]
Bot这边用到httpx的地方只有向Crawler添加/删除订阅的时候，是不是Crawler的URL写错了？如果是Crawler那边的报错，偶尔出现的话是平台API抽风，不用管
